// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSahzgg4ioHPWX0P8Nvreph-R3TVTVIo4',
    appId: '1:665804078241:web:306bc1d52bb27eb2b804e0',
    messagingSenderId: '665804078241',
    projectId: 'readintofirebase',
    authDomain: 'readintofirebase.firebaseapp.com',
    databaseURL: 'https://readintofirebase-default-rtdb.firebaseio.com',
    storageBucket: 'readintofirebase.appspot.com',
    measurementId: 'G-L1TDBQCECG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOR7fWbkTFyLynesWL_fNV2AMfNDShZlU',
    appId: '1:665804078241:android:944077cb73851181b804e0',
    messagingSenderId: '665804078241',
    projectId: 'readintofirebase',
    databaseURL: 'https://readintofirebase-default-rtdb.firebaseio.com',
    storageBucket: 'readintofirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGiuT_cC1ztyfG1H1Ub8rtOK-kd-_rNQU',
    appId: '1:665804078241:ios:dd01c64b8f470aefb804e0',
    messagingSenderId: '665804078241',
    projectId: 'readintofirebase',
    databaseURL: 'https://readintofirebase-default-rtdb.firebaseio.com',
    storageBucket: 'readintofirebase.appspot.com',
    androidClientId: '665804078241-v8p5gbaomvk3lg2fblk41og7292raaq4.apps.googleusercontent.com',
    iosClientId: '665804078241-2u2gn4iqluossqof9uc4s5r2ete5rjaa.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentify',
  );
}
